/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/eJQAlKtYKRh
 */
import { ScrollArea } from '@/components/ui/scroll-area';
import Image from 'next/image';
import PersonalWriting from './personal-writing';

import { Card, CardContent } from '@/components/ui/card';
import {
  Carousel,
  CarouselContent,
  CarouselItem,
  CarouselNext,
  CarouselPrevious
} from '@/components/ui/carousel';

export function AboutAuthor() {
  return (
    <main className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
      <section className="flex flex-col items-start gap-6 md:flex-row md:gap-12">
        <img
          alt="Author's Image"
          className="aspect-[4/5] w-full overflow-hidden rounded-lg border border-gray-200 object-cover dark:border-gray-800"
          height={500}
          src="https://www.womenshistory.org/sites/default/files/styles/main_image/public/images/2021-04/Toni-Morrison-Square.png"
          width={400}
        />
        <div className="flex flex-col gap-4">
          <div className="space-y-2">
            <h1 className="text-4xl font-bold">Parisa Yazdi</h1>
            <p className="text-lg text-gray-500 dark:text-gray-400">Author and Writer</p>
          </div>
          <p className="text-lg leading-relaxed">
            John Doe is a renowned author and writer known for his captivating storytelling and
            unique writing style. His works have been published in numerous journals and magazines
            and have been translated into multiple languages. John's passion for writing is evident
            in his engaging narratives and compelling characters.
          </p>
          <p className="text-lg leading-relaxed">
            John Doe is a renowned author and writer known for his captivating storytelling and
            unique writing style. His works have been published in numerous journals and magazines
            and have been translated into multiple languages. John's passion for writing is evident
            in his engaging narratives and compelling characters.
          </p>
          <p className="text-lg leading-relaxed">
            John Doe is a renowned author and writer known for his captivating storytelling and
            unique writing style. His works have been published in numerous journals and magazines
            and have been translated into multiple languages. John's passion for writing is evident
            in his engaging narratives and compelling characters.
          </p>
        </div>
      </section>
      <section>
        <h2 className="mb-6 mt-24 text-3xl font-bold">Personal Writings</h2>
        <Carousel
          opts={{
            align: 'start'
          }}
          className="w-full max-w-7xl"
        >
          <CarouselContent>
            {Array.from({ length: 4 }).map((_, index) => (
              <CarouselItem key={index} className="md:basis-1/2 lg:basis-1/3">
                <div className="p-1">
                  <PersonalWriting />
                </div>
              </CarouselItem>
            ))}
          </CarouselContent>
          <CarouselPrevious />
          <CarouselNext />
        </Carousel>
      </section>
      <section>
        <h2 className="mb-6 mt-24 text-3xl font-bold">Personal Videos</h2>
        <Carousel
          opts={{
            align: 'start'
          }}
          className="w-full max-w-7xl"
        >
          <CarouselContent>
            {Array.from({ length: 4 }).map((_, index) => (
              <CarouselItem key={index} className="md:basis-1/2 lg:basis-1/3">
                <div className="p-1">
                  <PersonalWriting />
                </div>
              </CarouselItem>
            ))}
          </CarouselContent>
          <CarouselPrevious />
          <CarouselNext />
        </Carousel>
      </section>

      {/* <h2 className="mb-6 mt-12 text-3xl font-bold">Personal Writings</h2>
      <section className=" flex gap-5 ">
        <PersonalWriting />
        <PersonalWriting />
        <PersonalWriting />
      </section> */}
    </main>
  );
}
