/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/a4QWmNyTrEQ
 */
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { CardContent, Card } from '@/components/ui/card';

export function AppointmentRedirect() {
  return (
    <div className="min-h-3/4 flex flex-col items-center justify-center border-b border-black bg-gray-100 py-32 ">
      <Card className="mx-auto w-full max-w-2xl overflow-hidden rounded-lg shadow-md">
        <CardContent className="p-6">
          <div className="mb-4 flex items-center justify-center">
            <CheckIcon className="h-12 w-12 text-green-500" />
          </div>
          <h2 className="text-center text-2xl font-semibold text-gray-800 dark:text-white">
            Appointment Confirmed!
          </h2>
          <p className="mt-2 text-center text-gray-600 dark:text-gray-200">
            Thank you for your payment. Your appointment has been successfully booked. Please check
            your email for the appointment details and payment summary.
          </p>
          <div className="mt-8">
            <Link className="flex h-full w-full items-center justify-center" href="#">
              <Button className="h-12 w-full" variant="default">
                Return to Homepage
              </Button>
            </Link>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}

function CheckIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="20 6 9 17 4 12" />
    </svg>
  );
}
