/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/m09Z54fawez
 */
import { AvatarImage, AvatarFallback, Avatar } from '@/components/ui/avatar';
import { CardTitle, CardHeader, CardContent, Card } from '@/components/ui/card';
import { Button } from './ui/button';
import Link from 'next/link';

export function ClassInformation({
  name,
  instructor,
  description,
  duration,
  image,
  link,
  initials
}: {
  name: string;
  instructor?: string;
  description: string;
  duration?: string;
  image: string;
  link?: string;
  initials?: string;
}) {
  return (
    <section className="w-full py-12 md:py-14 lg:py-12">
      <div className="container px-4 md:px-6">
        <div className="grid gap-6 lg:grid-cols-2 lg:gap-12 xl:grid-cols-3">
          <div className="space-y-6 lg:col-span-2">
            <h1 className="text-4xl font-bold">{name}</h1>
            <div className="space-y-6 md:mt-32 md:hidden">
              <Card>
                <CardHeader>
                  <CardTitle>Course Details</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="space-y-4">
                    <div className="flex items-center space-x-2">
                      <BookIcon className="h-5 w-5 text-gray-500 dark:text-gray-400" />
                      <div className="font-medium">Course Name</div>
                      <div className="text-sm text-gray-500 dark:text-gray-400">{name}</div>
                    </div>
                    <div className="flex items-center space-x-2">
                      <ClockIcon className="h-5 w-5 text-gray-500 dark:text-gray-400" />
                      <div className="font-medium">Duration</div>
                      <div className="text-sm text-gray-500 dark:text-gray-400">{duration}</div>
                    </div>
                    <div className="flex items-center space-x-2">
                      <UserIcon className="h-5 w-5 text-gray-500 dark:text-gray-400" />
                      <div className="font-medium">Instructor</div>
                      <div className="text-sm text-gray-500 dark:text-gray-400">{instructor}</div>
                    </div>
                    <div className="flex items-start space-x-2">
                      <ClipboardIcon className="mt-1 h-5 w-5 text-gray-500 dark:text-gray-400" />
                      <div className="font-medium">Description</div>
                      <div className="text-sm text-gray-500 dark:text-gray-400">
                        {description.slice(0, 200) + '...'}
                      </div>
                    </div>
                    <div className="mt-8 flex w-full items-center justify-center">
                      <Link href={link || ''}>
                        <Button className="w-full rounded-lg bg-black px-4 py-2 text-white">
                          Enroll Now
                        </Button>
                      </Link>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </div>
            <div className="flex justify-between ">
              <div className="flex items-center space-x-2">
                <Avatar>
                  <AvatarImage alt="Instructor" src="" />
                  <AvatarFallback>{initials}</AvatarFallback>
                </Avatar>
                <div>
                  <div className="font-medium">{instructor}</div>
                  <div className="text-sm text-gray-500 dark:text-gray-400">Instructor</div>
                </div>
              </div>
              <div className="flex items-center space-x-4">
                <div className="flex items-center space-x-2">
                  <ClockIcon className="h-5 w-5 text-gray-500 dark:text-gray-400" />
                  <div>{duration}</div>
                </div>
              </div>
            </div>
            <div className="mt-4">
              <img
                alt="Featured Image"
                className="h-64 w-full rounded-lg object-cover shadow-md"
                height="200"
                src={image}
                style={{
                  aspectRatio: '400/200',
                  objectFit: 'cover'
                }}
                width="400"
              />
            </div>

            <p className="text-lg text-gray-500 dark:text-gray-400">{description}</p>
          </div>
          <div className="space-y-6  xl:mt-32">
            <Card>
              <CardHeader>
                <CardTitle>Course Details</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  <div className="flex items-center space-x-2">
                    <BookIcon className="h-5 w-5 text-gray-500 dark:text-gray-400" />
                    <div className="font-medium">Course Name</div>
                    <div className="text-sm text-gray-500 dark:text-gray-400">{name}</div>
                  </div>
                  <div className="flex items-center space-x-2">
                    <ClockIcon className="h-5 w-5 text-gray-500 dark:text-gray-400" />
                    <div className="font-medium">Duration</div>
                    <div className="text-sm text-gray-500 dark:text-gray-400">{duration}</div>
                  </div>
                  <div className="flex items-center space-x-2">
                    <UserIcon className="h-5 w-5 text-gray-500 dark:text-gray-400" />
                    <div className="font-medium">Instructor</div>
                    <div className="text-sm text-gray-500 dark:text-gray-400">{instructor}</div>
                  </div>
                  <div className="flex items-start space-x-2">
                    <ClipboardIcon className="mt-1 h-5 w-5 text-gray-500 dark:text-gray-400" />
                    <div className="font-medium">Description</div>
                    <div className="text-sm text-gray-500 dark:text-gray-400">
                      {description.slice(0, 200) + '...'}
                    </div>
                  </div>
                  <div className="mt-8 flex w-full items-center justify-center">
                    <Link href={link || ''}>
                      <Button className="w-full rounded-lg bg-black px-4 py-2 text-white">
                        Enroll Now
                      </Button>
                    </Link>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </section>
  );
}

function ClockIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <polyline points="12 6 12 12 16 14" />
    </svg>
  );
}

function BookIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20" />
    </svg>
  );
}

function UserIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  );
}

function ClipboardIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="8" height="4" x="8" y="2" rx="1" ry="1" />
      <path d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2" />
    </svg>
  );
}
