/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/isA11HotT85
 */
import Link from 'next/link';

export function GalleryComp() {
  return (
    <div className="mx-auto w-full max-w-7xl p-4">
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
        <div className="group relative">
          <img
            alt="Art Piece 1"
            className="aspect-square w-full overflow-hidden rounded-lg border border-gray-200 object-cover dark:border-gray-800"
            height="400"
            src="/placeholder.svg"
            width="400"
          />
          <div className="absolute inset-0 flex items-center justify-center bg-black bg-opacity-50 opacity-0 transition-opacity group-hover:opacity-100">
            <p className="text-lg text-white">Art Piece 1</p>
          </div>
        </div>
        <div className="group relative">
          <img
            alt="Art Piece 2"
            className="aspect-square w-full overflow-hidden rounded-lg border border-gray-200 object-cover dark:border-gray-800"
            height="400"
            src="/placeholder.svg"
            width="400"
          />
          <div className="absolute inset-0 flex items-center justify-center bg-black bg-opacity-50 opacity-0 transition-opacity group-hover:opacity-100">
            <p className="text-lg text-white">Art Piece 2</p>
          </div>
        </div>
        <div className="group relative">
          <img
            alt="Art Piece 3"
            className="aspect-square w-full overflow-hidden rounded-lg border border-gray-200 object-cover dark:border-gray-800"
            height="400"
            src="/placeholder.svg"
            width="400"
          />
          <div className="absolute inset-0 flex items-center justify-center bg-black bg-opacity-50 opacity-0 transition-opacity group-hover:opacity-100">
            <p className="text-lg text-white">Art Piece 3</p>
          </div>
        </div>
        <div className="group relative">
          <img
            alt="Art Piece 4"
            className="aspect-square w-full overflow-hidden rounded-lg border border-gray-200 object-cover dark:border-gray-800"
            height="400"
            src="/placeholder.svg"
            width="400"
          />
          <div className="absolute inset-0 flex items-center justify-center bg-black bg-opacity-50 opacity-0 transition-opacity group-hover:opacity-100">
            <p className="text-lg text-white">Art Piece 4</p>
          </div>
        </div>
        <div className="group relative">
          <img
            alt="Art Piece 5"
            className="aspect-square w-full overflow-hidden rounded-lg border border-gray-200 object-cover dark:border-gray-800"
            height="400"
            src="/placeholder.svg"
            width="400"
          />
          <div className="absolute inset-0 flex items-center justify-center bg-black bg-opacity-50 opacity-0 transition-opacity group-hover:opacity-100">
            <p className="text-lg text-white">Art Piece 5</p>
          </div>
        </div>
        <div className="group relative">
          <img
            alt="Art Piece 6"
            className="aspect-square w-full overflow-hidden rounded-lg border border-gray-200 object-cover dark:border-gray-800"
            height="400"
            src="/placeholder.svg"
            width="400"
          />
          <div className="absolute inset-0 flex items-center justify-center bg-black bg-opacity-50 opacity-0 transition-opacity group-hover:opacity-100">
            <p className="text-lg text-white">Art Piece 6</p>
          </div>
        </div>
        <div className="group relative">
          <img
            alt="Art Piece 7"
            className="aspect-square w-full overflow-hidden rounded-lg border border-gray-200 object-cover dark:border-gray-800"
            height="400"
            src="/placeholder.svg"
            width="400"
          />
          <div className="absolute inset-0 flex items-center justify-center bg-black bg-opacity-50 opacity-0 transition-opacity group-hover:opacity-100">
            <p className="text-lg text-white">Art Piece 7</p>
          </div>
        </div>
        <div className="group relative">
          <img
            alt="Art Piece 8"
            className="aspect-square w-full overflow-hidden rounded-lg border border-gray-200 object-cover dark:border-gray-800"
            height="400"
            src="/placeholder.svg"
            width="400"
          />
          <div className="absolute inset-0 flex items-center justify-center bg-black bg-opacity-50 opacity-0 transition-opacity group-hover:opacity-100">
            <p className="text-lg text-white">Art Piece 8</p>
          </div>
        </div>
      </div>
      <div className="mt-4 w-full">
        <Link
          className="inline-flex h-10 items-center justify-center rounded-md bg-gray-900 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
          href="/"
        >
          Back to Home
        </Link>
      </div>
    </div>
  );
}
